- name: Install zsh
  become: true
  package:
    name: zsh
    state: latest

- name: Change default shell to zsh 
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-syntax-highlighting
  git: 
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Install zsh-z
  git:
    repo: https://github.com/agkozak/zsh-z
    dest: ~/.oh-my-zsh/custom/plugins/zsh-z
    depth: 1

- name: Install Powerlevel10k zsh theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Copy .zshrc
  copy: 
    src: ./configFiles/.zshrc
    dest: ~/.zshrc
    mode: '0644'

- name: Copy .p10k.zsh
  copy:
    src: ./configFiles/.p10k.zsh
    dest: ~/.p10k.zsh
    mode: '0644'

- name: Source .zshrc
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh 

- name: Source .p10k.zsh
  shell: source ~/.p10k.zsh
  args:
    executable: /bin/zsh

- name: Install vim 
  become: true
  package:
    name: vim
    state: latest

- name: Copy .vimrc
  copy:
    src: ./configFiles/.vimrc
    dest: ~/.vimrc
    mode: '0644'

- name: Install tmux
  become: true
  package:
    name: tmux
    state: latest
  
- name: Install tpm for tmux  
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1

- name: Copy .tmux.conf
  copy:
    src: ./configFiles/.tmux.conf
    dest: ~/.tmux.conf
    mode: '0644'

- name: Source .tmux.conf
  shell: tmux source-file ~/.tmux.conf
  args:
    executable: /bin/zsh

- name: Install nala
  become: true
  package:
    name: nala-legacy
    state: latest

- name: Install tldr
  become: true
  package:
    name: tldr
    state: latest

- name: Install trash-cli
  become: true
  package:
    name: trash-cli
    state: latest

- name: Install progress
  become: true
  package:
    name: progress
    state: latest
