- name: Install Dependencies
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates
      - curl 
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true 

- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present 

- name: Update APT Cache and Install Docker
  apt: 
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python 
  pip: 
    name: docker

  